version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - mongoDbUrl=mongodb://mongo:27017/todolistdb
    depends_on:
      - mongo
    networks:
      - todo-network

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

volumes:
  mongo-data:

networks:
  todo-network:
    driver: bridge
